title: "Henry Leou"
author: "Henry Leou"
email: "henryleou@berkeley.com" 
description: >
  Embedded Systems | AI | Cellular | C++ & Python | Qualcomm | Georgia Tech OMSCS

url: "https://henryleou.github.io"
baseurl: ""

# Navigation bar
navbar-links:
  About Me: "aboutme"
  Projects: "projects"
  Resume: "resume"
  # Blog: "https://medium.com/@henryleou"

# Social links
social-network-links:
  github: henryleou
  linkedin: henryleou
  email: henryleou@berkeley.com

# Footer
footer-links-active:
  github: true
  linkedin: true
  email: true

# Build settings
markdown: kramdown
highlighter: rouge

# Optional analytics
# google_analytics: UA-XXXXXXXXX-X

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
